# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_testusername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testusername',
            old_name='name',
            new_name='username',
        ),
    ]
